# Generated by Django 3.1.1 on 2020-09-29 00:31

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('personal', 'PERSONAL'), ('draft', 'DRAFT'), ('client', 'CLIENT')], default='personal', max_length=14)),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to=projects.models.img_upload_location)),
                ('liveURL', models.CharField(max_length=120)),
                ('playURL', models.CharField(max_length=120)),
                ('repoURL', models.CharField(max_length=120)),
                ('desc', models.CharField(max_length=160)),
                ('inProgress', models.BooleanField(default=False)),
                ('clientName', models.CharField(max_length=80)),
                ('clientImage', models.ImageField(blank=True, null=True, upload_to=projects.models.img_upload_location)),
                ('galleryText', models.TextField()),
            ],
        ),
    ]
