# Generated by Django 3.1.1 on 2020-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200928_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clientName',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='liveURL',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='playURL',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='repoURL',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
