# Generated by Django 3.1.1 on 2020-09-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='devicon_class',
            field=models.CharField(help_text='Name of skill for devicon-[skillname]-plain', max_length=40),
        ),
    ]
